/** Logical sound IDs for SFX. Paths relative to assets/sounds/Cute UI _ Interact Sound Effects Pack/AUDIO/ */
export const SOUND_IDS = [
  'customer_arrive',
  'customer_leave',
  'forge_tick',
  'forge_strike',
  'craft_complete',
  'gold_earned',
  'good_bought',
  'enchant_open',
  'enchant_complete',
  'enchant_tile_move',
  'enchant_finish_early',
  'haggle_open',
  'haggle_roll',
  'haggle_settle',
  'haggle_bust',
  'haggle_win',
  'milestone',
  'tier_unlock',
  'ui_hover',
  'game_start',
  'tab_click',
  'upgrade_purchase',
  'upgrade_click',
  'cooldown_ready',
  'reaction_masterwork',
  'reaction_good',
  'reaction_passable',
  'reaction_shoddy',
  'reaction_clock_tick',
  'reaction_buy',
  'settings_open',
] as const;

export type SoundId = (typeof SOUND_IDS)[number];

export const SOUND_PATHS: Record<SoundId, string> = {
  customer_arrive: 'Swoosh/SFX_Movement_Swoosh_Slow_1.wav',
  customer_leave: 'Swoosh/SFX_Movement_Swoosh_Med_1.wav',
  forge_tick: 'UI/Countdown/SFX_UI_Countdown_Blow_1.wav',
  forge_strike: 'Rattle/Metal/SFX_Rattle_Metal_1.wav',
  craft_complete: 'Powerup/SFX_Powerup_Bright_1.wav',
  gold_earned: 'Collect/Coin/SFX_Player_Collect_Coin_2.wav',
  good_bought: 'Powerup/SFX_Powerup_Bright_1.wav',
  enchant_open: 'UI/Click/Open_Close/SFX_UI_Button_Click_Open_1.wav',
  enchant_complete: 'Collect/Bright/SFX_Player_Collect_Bright_2.wav',
  enchant_tile_move: 'UI/Click/Generic/SFX_UI_Button_Click_Generic_1.wav',
  enchant_finish_early: 'UI/Click/Select/SFX_UI_Button_Click_Select_1.wav',
  haggle_open: 'UI/Click/Open_Close/SFX_UI_Button_Click_Open_1.wav',
  haggle_roll: 'Rattle/Plastic/SFX_Rattle_Plastic_Soft_1.wav',
  haggle_settle: 'UI/Click/Select/SFX_UI_Button_Click_Select_1.wav',
  haggle_bust: 'UI/Click/Negative/SFX_UI_Button_Click_Generic_Negative_1.wav',
  haggle_win: 'UI/Success/SFX_UI_Success_Bright_Pop_1.wav',
  milestone: 'Chimes/SFX_Chimes_Glowing_Stars_1.wav',
  tier_unlock: 'Firework/SFX_Firework_Explosion_1.wav',
  ui_hover: 'UI/Click/Generic/SFX_UI_Button_Click_Generic_1.wav',
  game_start: 'Chest_Open/SFX_Chest_Open_1.wav',
  tab_click: 'UI/Click/Select/SFX_UI_Button_Click_Select_1.wav',
  upgrade_purchase: 'UI/Success/SFX_UI_Success_Achievement_Pop_1.wav',
  upgrade_click: 'UI/Click/Select/SFX_UI_Button_Click_Select_1.wav',
  cooldown_ready: 'UI/Appear/SFX_UI_Appear_1.wav',
  reaction_masterwork: 'UI/Success/SFX_UI_Success_Bright_Pop_1.wav',
  reaction_good: 'UI/Click/Select/SFX_UI_Button_Click_Select_1.wav',
  reaction_passable: 'UI/Click/Generic/SFX_UI_Button_Click_Generic_1.wav',
  reaction_shoddy: 'UI/Click/Negative/SFX_UI_Button_Click_Generic_Negative_1.wav',
  reaction_clock_tick: '../freesound_community-clock-tick-101150.mp3',
  reaction_buy: 'Pop/Mouth/SFX_Pop_Mouth_High_1.wav',
  settings_open: 'UI/Click/Settings/SFX_UI_Button_Click_Settings_1.wav',
};
